### ISSUE TITLE
Program Error

### ISSUE THREAD

**Issue by secfb** [pingc0y/URLFinder#14]
1) I am getting the following error can you help?
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/38748801/190249451-5ff50174-6444-498c-95ae-af891aa86e75.png">

URLFinder-linux64= jsurlfinder
Error Code 
```powershell 
jsurlfinder -m 2 -s all -u $host
         __   __   ___ _           _
 /\ /\  /__\ / /  / __(_)_ __   __| | ___ _ __
/ / \ \/ \/// /  / _\ | | '_ \ / _` |/ _ \ '__|
\ \_/ / _  \ /___ /   | | | | | (_| |  __/ |
 \___/\/ \_\____\/    |_|_| |_|\__,_|\___|_|

Start Spider URL: http://testfire.net
Spider OK
panic: runtime error: index out of range [0] with length 0

goroutine 18 [running]:
main.appendJs({0xc0000ac700, 0xc0002dfdc0}, {0xc0000c41b0, 0x0})
        D:/URLFinder/main.go:807 +0x378
main.jsFind({0xc000142000, 0x2499}, {0x7fffc30e2f03, 0xc}, {0x7fffc30e2efc, 0x4}, {0x0, 0x0}, 0x1)
        D:/URLFinder/main.go:537 +0x3a5
main.spider({0x7fffc30e2efc, 0x13}, 0x0)
        D:/URLFinder/main.go:491 +0x6c5
created by main.start
        D:/URLFinder/main.go:136 +0x133
```
-------

2) In addition, I could not export the application as darwin arm.

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/38748801/190250149-a0d3ce46-d6f5-4760-acb7-5fc6156ed26a.png">

```powershell 
~/tool/URLFinder$ CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -o jsurlfinder main.go
main.go:8:2: cannot find package "github.com/fatih/color" in any of:
        /usr/local/go/src/github.com/fatih/color (from $GOROOT)
        /home/mehmetcihandogan/gopath/src/github.com/fatih/color (from $GOPATH)
        /google/gopath/src/github.com/fatih/color
main.go:9:2: cannot find package "gopkg.in/yaml.v2" in any of:
        /usr/local/go/src/gopkg.in/yaml.v2 (from $GOROOT)
        /home/mehmetcihandogan/gopath/src/gopkg.in/yaml.v2 (from $GOPATH)
        /google/gopath/src/gopkg.in/yaml.v2
```

**Comment by pingc0y** [comment]
1. Thanks for the feedback, the problem should be solved, download the new version to test.

2. It cannot be compiled because your environment does not have the package of color and yaml.v2, you need to download it first.

```
go get github.com/fatih/color
go get gopkg.in/yaml.v2
```
