### ISSUE TITLE
当使用-f参数运行一段时间后会报错

### ISSUE THREAD

**Issue by YanXi9999** [pingc0y/URLFinder#88]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0xd5a1e9]

goroutine 1 [running]:
github.com/pingc0y/URLFinder/util.GetProtocol({0xc00ae406a8, 0x16})
        /home/runner/work/URLFinder/URLFinder/util/utils.go:122 +0xc9
github.com/pingc0y/URLFinder/crawler.Run()
        /home/runner/work/URLFinder/URLFinder/crawler/run.go:111 +0x6d7
main.main()
        /home/runner/work/URLFinder/URLFinder/main.go:15 +0x37

**Comment by pingc0y** [comment]
是有这个问题 下次更新修复， 给域名加上完整的http协议可以规避这个报错

**Comment by wanheiqiyihu** [comment]
现在还没修
